# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghtelectroniccenter', '0004_auto_20170106_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buktitransfer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='id',
        ),
        migrations.RemoveField(
            model_name='warna',
            name='id',
        ),
        migrations.AddField(
            model_name='buktitransfer',
            name='kode_bukti',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produk',
            name='kode_produk',
            field=models.CharField(default=0, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='warna',
            name='kode_warna',
            field=models.CharField(default=0, max_length=7, primary_key=True, serialize=False),
        ),
    ]
