# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghtelectroniccenter', '0007_auto_20170113_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alamat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=50)),
                ('kota', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('jalan', models.CharField(max_length=100)),
                ('kode_pos', models.CharField(max_length=5)),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghtelectroniccenter.Customer')),
            ],
        ),
    ]
