# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghtelectroniccenter', '0008_alamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alamat',
            name='id_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alamat', to='ghtelectroniccenter.Customer'),
        ),
    ]
