# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghtelectroniccenter', '0009_auto_20170113_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='listcart',
            name='waktu_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barang_pesanan', to='ghtelectroniccenter.Cart'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='kode_produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='ghtelectroniccenter.Produk'),
        ),
    ]
